
CC=clang++

CFLAGS=-g -Wall -Wextra -Werror -pedantic --target=x86_64-pc-linux -fdeclspec

LIBS=cpu/sse.so cpu/avx.so cpu/avx512f.so

.PHONY: all libs clean

all: benchmark libs

libs: $(LIBS)

%.so: %.cpp
	$(CC) $(CFLAGS) -fPIC -shared -m$(patsubst cpu/%.so,%,$@) -o $@ $^

benchmark: benchmark.cpp
	$(CC) $(CFLAGS) -ldl -lOpenCL -o $@ $^

clean:
	rm -f benchmark $(LIBS)
