
CC=clang++

CFLAGS=-std=c++14 -Wall -Wextra -Werror -pedantic --target=x86_64-apple-darwin

LIBS_S=cpu/sse.dylib cpu/avx.dylib cpu/avx512f.dylib

.PHONY: all libs clean

all: benchmark libs

libs: cpu/scalar.dylib $(LIBS_S)

cpu/scalar.dylib: cpu/scalar.cpp
	$(CC) $(CFLAGS) -fPIC -shared -o $@ $^

%.dylib: %.cpp
	$(CC) $(CFLAGS) -fPIC -shared -m$(patsubst cpu/%.dylib,%,$@) -o $@ $^

benchmark: benchmark.cpp
	$(CC) $(CFLAGS) -ldl -o $@ $^

clean:
	rm -f benchmark cpu/scalar.dylib $(LIBS_S)
